In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectFromModel


In [2]:
dataset=pd.read_csv('Dataset.csv')

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
x=dataset.iloc[:,1:13].values
x

array([[15634602, 'Hargrave', 619, ..., 1, 1, 101348.88],
       [15647311, 'Hill', 608, ..., 0, 1, 112542.58],
       [15619304, 'Onio', 502, ..., 1, 0, 113931.57],
       ...,
       [15584532, 'Liu', 709, ..., 0, 1, 42085.58],
       [15682355, 'Sabbatini', 772, ..., 1, 0, 92888.52],
       [15628319, 'Walker', 792, ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y=dataset.iloc[:,13:].values
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

In [6]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [7]:
x[:,1]=lb.fit_transform(x[:,1])
x[:,3]=lb.fit_transform(x[:,3])
x[:,4]=lb.fit_transform(x[:,4])


In [8]:
x[:,5]

array([42, 41, 42, ..., 36, 42, 28], dtype=object)

In [9]:
feat_labels=['CustomerId','Surname','CreditScore','Geography','Gender','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
x_train

array([[15676909, 1818, 667, ..., 1, 0, 163830.64],
       [15749265, 414, 427, ..., 1, 1, 57098.0],
       [15582492, 1839, 535, ..., 1, 0, 185630.76],
       ...,
       [15574372, 1202, 738, ..., 1, 0, 181429.87],
       [15664035, 2122, 590, ..., 1, 1, 148750.16],
       [15592816, 2678, 623, ..., 1, 0, 118855.26]], dtype=object)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [13]:
from joblib import dump
dump(sc,'scalar1.save')

['scalar1.save']

In [14]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy',random_state=0)

In [15]:
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [16]:
import pickle 
pickle.dump(dt,open('decision.pk2','wb'))

In [17]:
for feature in zip(feat_labels,dt.feature_importances_):
    print(feature)

('CustomerId', 0.1156177189951204)
('Surname', 0.10892778334852683)
('CreditScore', 0.08892045630186339)
('Geography', 0.028613167087304336)
('Gender', 0.015294740553539098)
('Age', 0.20474374332366063)
('Tenure', 0.04975134557547193)
('Balance', 0.12117845089896963)
('NumOfProducts', 0.11035360966862098)
('HasCrCard', 0.010430384136864385)
('IsActiveMember', 0.03364451653610806)
('EstimatedSalary', 0.11252408357395026)


In [18]:
y_pred=dt.predict(x_test)
y_pred

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [19]:
y_test


array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.771